name: Deploy App to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_IP}}
          username: ${{secrets.HOST_USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            docker ps
